# Generated by Django 5.0.7 on 2024-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishes",
            name="DishesType",
            field=models.CharField(
                choices=[
                    ("light_meal", "简餐"),
                    ("desserts", "甜品"),
                    ("drinks", "饮品"),
                    ("the_rest", "其他"),
                ],
                default="the_rest",
                max_length=10,
            ),
        ),
    ]
